services:
  # db:
  #   image: postgres:16-alpine
  #   restart: unless-stopped
  #   ports:
  #     - "5433:5432"
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
  #     POSTGRES_DB: simon_bmkg
  #   volumes:
  #     - simon_db_data:/var/lib/postgresql/data
  #   healthcheck:
  #     test: ["CMD-SHELL", "pg_isready -U postgres"]
  #     interval: 5s
  #     timeout: 5s
  #     retries: 10

  app:
    image: chrisananta/simon-aloptama-bbmkg:latest
    restart: unless-stopped
    # depends_on:
    #   db:
    #     condition: service_healthy
    environment:
      NODE_ENV: production
      PORT: 3000
      DATABASE_URL: postgresql://Simon_Admn:Simon123AdmN12@192.168.88.8:5434/simon_bmkg?schema=public
      JWT_SECRET: 4c41502136bf4047b6718f8d5a972ff2e42eb37e9e204fc69e3f61e3fbefc561
      CORS_ORIGIN: "http://localhost:3000"
    ports:
      - "3000:3000"

volumes:
  simon_db_data:
